#plik_konfiguracyjny.conf

#okres kopii zapasowej
okres="1"

#katalogi źródłowy
cel=""

#host docelowy
host_docelowy=""

#katalog lokalny dla kopii bieżącej
katalog_z_kopiami="cel"

#katalog tymczasowy dla kopi archiwalnych przed wysłaniem ich na hosta zdalnego
magazyn=""
