#plik_konfiguracyjny.conf

#czy chcesz żeby skrypt działał tak jeśli tak nie jeśli nie
aktywacja="tak"


#typ okresu kopii zapasowej D(dni) T(tygodnie) M(miesiące)
okres_typ="T"

#co ile wybranego typu kończy się okres
okres="2"

#katalogi źródłowy
cel="C:\prace"

#katalog lokalny dla kopii bieżącej
katalog_z_kopiami="C:\skrypt_bash\skrypty_pow-oki_zadanie\cel"

#katalog tymczasowy dla kopi archiwalnych przed wysłaniem ich na hosta zdalnego
magazyn="C:/skrypt_bash/skrypty_pow-oki_zadanie/magazayn/"

#katalog do którego wysyłane będą logi
logi="C:\skrypt_bash\skrypty_pow-oki_zadanie\logi"

#host docelowy
host_docelowy="test"

#ip lub domena
ipdom="Pipek"


#katalog docelowy u hosta docelowego 
katalog_docelowy="C:\skrypt_bash\skrypty_pow-oki_zadanie\magazyn2"



