#plik_konfiguracyjny.conf

#czy chcesz żeby skrypt działał "tak" jeśli tak, "nie" jeśli nie
aktywacja="tak"


#typ okresu kopii zapasowej D(dni) T(tygodnie) M(miesiące)
okres_typ="D"

#co ile jednostek wybranego typu kończy się okres
okres="0"

#katalog źródłowy(to co będziesz kopiować)
cel="C:\skrypt\kopiowany_folder"

#katalog lokalny dla kopii bieżącej(tutaj będą niezarchiwizowane kopie)
katalog_z_kopiami="C:\skrypt\cel"

#katalog tymczasowy dla kopi archiwalnych przed wysłaniem ich na hosta zdalnego
#używaj bez względu na system / a nie \ np. w windowsie przykład C:/skrypt/magazayn/
magazyn="C:/skrypt/magazayn/"

#katalog do którego wysyłane będą logi
logi="C:\skrypt\logi"

#host docelowy(nazwa np student22 bez @)
host_docelowy="test"

#ip lub domena(np. serwer4 lub 192.168.0.112)
ipdom="localhost"


#katalog docelowy u hosta docelowego (ścierzka na hoście)
katalog_docelowy="C:\skrypt\magazyn2"



